name: Test-Build
on:
  push:
    branches:
      - main
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # INstall Node on the runner
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      # Install the newman command line utility and also install the html extra reporter
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Make directory to upload the test results
      - name: Make Directory for results
        run: mkdir -p test_results

      # Run the POSTMAN collection
      - name: Run POSTMAN collection
        run: |
          newman run pet.json -r htmlextra --reporter-htmlextra-export test_results/htmlreport.html --reporter-htmlextra-darkTheme  > test_results/runreport1.html
                   
      # Upload the contents of Test Results directory to workspace
      - name: Output the run Details
        uses: actions/upload-artifact@v2
        with:
          name: test-run-reports
          path: test_results