name: Test postman-newman-ghActions

on:
  push:
    branches: [ "main" ]
jobs:
  test-api:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install Node
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          
      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
          
      - name: Make the Directory to result
        run: mkdr -p testResults
        
      - name: run Postman
        run: |
          newman run petstore.collection.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme > testResults/runreport1.html
      
      - name: outputs the run details
        uses: actions/upload-artifact@v2
        with:
          name: RunReports
          path: testResults
